jms_serializer:
    metadata:
        auto_detection: true
        directories:
            FOSUB:
                namespace_prefix: FOS\UserBundle
                path: '%kernel.root_dir%/Serializer/FOSUB'
